fix navbar zIndex bug
craftzdog/craftzdog-homepage pull request #38
Opened 2022-06-18 20:01 UTC by m1xa4kala

2022-06-19 09:25 UTC, m1xa4kala commented
#37

2022-06-20 04:35 UTC, craftzdog requested changes

2022-06-20 04:35 UTC, craftzdog commented on components/navbar.js
> +      zIndex={10}
Can you change it to `2`?

2022-06-20 07:08 UTC, m1xa4kala commented on components/navbar.js
> +      zIndex={10}
Yep, no problem)

2022-06-20 08:03 UTC, merged